const QUERY_KEYS = {
  REGISTER: "REGISTER",
  LOGIN: "LOGIN",
  VERIFY_EMAIL: "VERIFY_EMAIL",
  RESEND_VERIFY_EMAIL_OTP: "RESEND_VERIFY_EMAIL_OTP",
  PROFILE: "PROFILE",
  SEARCH_FRIENDS: "SEARCH_FRIENDS",
  SEND_CONNECTION_REQUEST: "SEND_CONNECTION_REQUEST",
  RESPOND_ON_CONNECTION_REQUEST: "RESPOND_ON_CONNECTION_REQUEST",
};

export default QUERY_KEYS;
