const QUERY_KEYS = {
  REGISTER: "REGISTER",
  LOGIN: "LOGIN",
  VERIFY_EMAIL: "VERIFY_EMAIL",
  RESEND_VERIFY_EMAIL_OTP: "RESEND_VERIFY_EMAIL_OTP",
  PROFILE: "PROFILE",
};

export default QUERY_KEYS;
