const SOCKET_EVENTS = {
  DISCONNECT: "disconnect",
  CONNECT_ERROR: "connect_error",

  CONNECTED: "CONNECTED",
  NEW_CONNECTION_ADDED: "NEW_CONNECTION_ADDED",

  STATUS_UPDATE: (userId) => `STATUS-UPDATE-${userId}`,
  GET_STATUS: "GET_STATUS",
  MARK_MESSAGE_AS_SEEN: "MARK_MESSAGE_AS_SEEN",
  MARKED_MESSAGE_AS_SEEN: "MARKED_MESSAGE_AS_SEEN",
};

export default SOCKET_EVENTS;
